/*In production, this endpoint would return dynamic data
generated by the backend every time a user takes an action
(follow, connection, share, etc.)*/

import type { Activity } from "../../types/activity";

const API_URL =
  "https://my-json-server.typicode.com/gemmaadev/it-academy-alumni-api/activity";

export const getActivity = async (
  onError: (error: Error | unknown) => void,
): Promise<Activity[]> => {
  try {
    const response = await fetch(API_URL);
    if (!response.ok) {
      throw new Error(`Error loading recent activity`);
    }

    const activity: Activity[] = await response.json();
    return activity;
  } catch (error: Error | unknown) {
    console.error("Error fetching activity:", error);
    onError(error);
    throw error;
  }
};
